### ISSUE TITLE
Incorrect name in package.xml/CMakeLists.txt or directory

### ISSUE THREAD

**Issue by dgerod** [KCL-Planning/ROSPlan_interface_Turtlebot2#2]
The name of the package is "rosplan_interface_turtlebot" but the directory is named as "rosplan_interface_turtlebot2".

**Comment by m312z** [comment]
Thanks for the catch!

I've updated the package and CmakeLists to the correct name: "rosplan_interface_turtlebot2"
This should not break any existing git clones, but any launch files will have to updated.

Michael
